from core.database import Base
from datetime import datetime
from sqlalchemy import Boolean, Column, DateTime, Float, Integer, String


class Restaurant_settings(Base):
    __tablename__ = "restaurant_settings"
    __table_args__ = {"extend_existing": True}

    id = Column(Integer, primary_key=True, index=True, autoincrement=True, nullable=False)
    restaurant_name = Column(String, nullable=False)
    phone = Column(String, nullable=True)
    address = Column(String, nullable=True)
    opening_hours = Column(String, nullable=True)
    logo_url = Column(String, nullable=True)
    restaurant_status = Column(String, nullable=True)
    busy_message = Column(String, nullable=True)
    estimated_wait_time = Column(String, nullable=True)
    delivery_enabled = Column(Boolean, nullable=True)
    delivery_schedule_enabled = Column(Boolean, nullable=True, default=False, server_default='false')
    delivery_start_time = Column(String, nullable=True, default='16:00', server_default='16:00')
    delivery_end_time = Column(String, nullable=True, default='01:00', server_default='01:00')
    delivery_charges = Column(String, nullable=True)
    estimated_delivery_time = Column(String, nullable=True)
    restaurant_lat = Column(String, nullable=True)
    restaurant_lng = Column(String, nullable=True)
    near_radius = Column(String, nullable=True)
    far_radius = Column(String, nullable=True)
    near_charge = Column(String, nullable=True)
    far_charge = Column(String, nullable=True)
    auto_schedule_enabled = Column(Boolean, nullable=True)
    auto_open_time = Column(String, nullable=True)
    auto_close_time = Column(String, nullable=True)
    service_fee_enabled = Column(Boolean, nullable=True)
    service_fee_amount = Column(Float, nullable=True)
    service_fee_type = Column(String, nullable=True)
    small_order_fee_enabled = Column(Boolean, nullable=True)
    small_order_fee_amount = Column(Float, nullable=True)
    small_order_fee_threshold = Column(Float, nullable=True)
    service_fee_applies_to = Column(String, nullable=True)
    cash_enabled_pickup = Column(Boolean, nullable=True)
    card_enabled_pickup = Column(Boolean, nullable=True)
    cash_enabled_delivery = Column(Boolean, nullable=True)
    card_enabled_delivery = Column(Boolean, nullable=True)
    allowed_country_codes = Column(String, nullable=True)
    blog_enabled = Column(Boolean, nullable=True)
    allow_cancel_preparing = Column(Boolean, nullable=True)
    allow_cancel_ready = Column(Boolean, nullable=True)
    allow_modify_preparing = Column(Boolean, nullable=True)
    order_accept_timeout_minutes = Column(Integer, nullable=True)
    order_expire_timeout_minutes = Column(Integer, nullable=True)
    checkout_flow = Column(String, nullable=True, default='two_step', server_default='two_step')
    tax_percent = Column(Float, nullable=True, default=0, server_default='0')
    vat_included = Column(Boolean, nullable=True, default=False, server_default='false')
    banner_text = Column(String, nullable=True, default='', server_default='')
    offer_text = Column(String, nullable=True, default='', server_default='')

    # Customer homepage controls (database-backed; shared by every device).
    show_branding = Column(Boolean, nullable=True, default=True, server_default='true')
    show_notifications = Column(Boolean, nullable=True, default=True, server_default='true')
    show_status_banner = Column(Boolean, nullable=True, default=True, server_default='true')
    show_offers = Column(Boolean, nullable=True, default=True, server_default='true')
    show_quick_actions = Column(Boolean, nullable=True, default=True, server_default='true')
    show_menu_action = Column(Boolean, nullable=True, default=True, server_default='true')
    show_deals_action = Column(Boolean, nullable=True, default=True, server_default='true')
    show_orders_action = Column(Boolean, nullable=True, default=True, server_default='true')
    show_contact_action = Column(Boolean, nullable=True, default=True, server_default='true')
    show_popular_items = Column(Boolean, nullable=True, default=True, server_default='true')
    show_reviews = Column(Boolean, nullable=True, default=True, server_default='true')
    show_restaurant_info = Column(Boolean, nullable=True, default=True, server_default='true')
    show_bottom_nav = Column(Boolean, nullable=True, default=True, server_default='true')
    popular_auto_enabled = Column(Boolean, nullable=True, default=True, server_default='true')
    popular_manual_enabled = Column(Boolean, nullable=True, default=True, server_default='true')
    popular_max_items = Column(Integer, nullable=True, default=6, server_default='6')

    # Admin Orders page can enable automatic rider assignment. Default OFF so
    # existing shops keep manual control until Admin explicitly turns it on.
    auto_assign_rider_enabled = Column(Boolean, nullable=True, default=False, server_default='false')

    created_at = Column(DateTime(timezone=True), default=datetime.now)
    updated_at = Column(DateTime(timezone=True), default=datetime.now, onupdate=datetime.now)
