"""auto update

Revision ID: 0599806515f7
Revises: 172f5ac7437d
Create Date: 2026-07-19 19:13:34.555151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0599806515f7'
down_revision: Union[str, Sequence[str], None] = '172f5ac7437d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_settings', sa.Column('allowed_country_codes', sa.String(), nullable=True))
    op.add_column('restaurant_settings', sa.Column('blog_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_settings', 'blog_enabled')
    op.drop_column('restaurant_settings', 'allowed_country_codes')
    # ### end Alembic commands ###