"""auto update

Revision ID: 6320e57d68ab
Revises: f427a71d45c6
Create Date: 2026-07-18 11:43:20.398086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6320e57d68ab'
down_revision: Union[str, Sequence[str], None] = 'f427a71d45c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('has_extras', sa.Boolean(), server_default='true', nullable=True))
    op.alter_column('menu_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=True)
    op.add_column('restaurant_settings', sa.Column('restaurant_status', sa.String(), server_default='open', nullable=True))
    op.add_column('restaurant_settings', sa.Column('busy_message', sa.String(), server_default='We are currently very busy. Your order may take longer than usual.', nullable=True))
    op.add_column('restaurant_settings', sa.Column('estimated_wait_time', sa.String(), server_default='30-45 min', nullable=True))
    op.alter_column('restaurant_settings', 'opening_hours',
               existing_type=sa.VARCHAR(),
               server_default='Daily 3:00 PM - 2:00 AM',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_settings', 'opening_hours',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Daily 3:00 PM – 2:00 AM'::character varying"),
               existing_nullable=True)
    op.drop_column('restaurant_settings', 'estimated_wait_time')
    op.drop_column('restaurant_settings', 'busy_message')
    op.drop_column('restaurant_settings', 'restaurant_status')
    op.alter_column('menu_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_column('menu_items', 'has_extras')
    # ### end Alembic commands ###