"""auto update

Revision ID: 6caad6e08bac
Revises: d09be5eac61a
Create Date: 2026-07-18 13:49:27.650986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6caad6e08bac'
down_revision: Union[str, Sequence[str], None] = 'd09be5eac61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('first_order_only', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('restaurant_settings', sa.Column('delivery_enabled', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('restaurant_settings', sa.Column('delivery_charges', sa.String(), server_default='5', nullable=True))
    op.add_column('restaurant_settings', sa.Column('estimated_delivery_time', sa.String(), server_default='30-45 min', nullable=True))
    op.add_column('restaurant_settings', sa.Column('restaurant_lat', sa.String(), server_default='25.1288', nullable=True))
    op.add_column('restaurant_settings', sa.Column('restaurant_lng', sa.String(), server_default='56.3264', nullable=True))
    op.add_column('restaurant_settings', sa.Column('near_radius', sa.String(), server_default='5', nullable=True))
    op.add_column('restaurant_settings', sa.Column('far_radius', sa.String(), server_default='15', nullable=True))
    op.add_column('restaurant_settings', sa.Column('near_charge', sa.String(), server_default='5', nullable=True))
    op.add_column('restaurant_settings', sa.Column('far_charge', sa.String(), server_default='15', nullable=True))
    op.add_column('restaurant_settings', sa.Column('auto_schedule_enabled', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('restaurant_settings', sa.Column('auto_open_time', sa.String(), server_default='15:00', nullable=True))
    op.add_column('restaurant_settings', sa.Column('auto_close_time', sa.String(), server_default='02:00', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_settings', 'auto_close_time')
    op.drop_column('restaurant_settings', 'auto_open_time')
    op.drop_column('restaurant_settings', 'auto_schedule_enabled')
    op.drop_column('restaurant_settings', 'far_charge')
    op.drop_column('restaurant_settings', 'near_charge')
    op.drop_column('restaurant_settings', 'far_radius')
    op.drop_column('restaurant_settings', 'near_radius')
    op.drop_column('restaurant_settings', 'restaurant_lng')
    op.drop_column('restaurant_settings', 'restaurant_lat')
    op.drop_column('restaurant_settings', 'estimated_delivery_time')
    op.drop_column('restaurant_settings', 'delivery_charges')
    op.drop_column('restaurant_settings', 'delivery_enabled')
    op.drop_column('offers', 'first_order_only')
    # ### end Alembic commands ###