"""auto update

Revision ID: 8868ace2ad6f
Revises: 2b87d39b57bf
Create Date: 2026-07-20 18:54:38.422137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8868ace2ad6f'
down_revision: Union[str, Sequence[str], None] = '2b87d39b57bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_sessions', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('idx_customer_sessions_user_id'), table_name='customer_sessions')
    op.create_index(op.f('ix_customer_sessions_user_id'), 'customer_sessions', ['user_id'], unique=False)
    op.add_column('delivery_assignments', sa.Column('delivery_charge', sa.Float(), server_default='0', nullable=True))
    op.add_column('delivery_assignments', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('delivery_assignments', sa.Column('zone_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_assignments', 'zone_name')
    op.drop_column('delivery_assignments', 'distance_km')
    op.drop_column('delivery_assignments', 'delivery_charge')
    op.drop_index(op.f('ix_customer_sessions_user_id'), table_name='customer_sessions')
    op.create_index(op.f('idx_customer_sessions_user_id'), 'customer_sessions', ['user_id'], unique=False)
    op.alter_column('customer_sessions', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###