"""auto update

Revision ID: 8a77bbca060e
Revises: 0599806515f7
Create Date: 2026-07-20 04:58:27.071585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a77bbca060e'
down_revision: Union[str, Sequence[str], None] = '0599806515f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('usage_limit_per_customer', sa.Integer(), server_default='1', nullable=True))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.add_column('restaurant_settings', sa.Column('service_fee_type', sa.String(), nullable=True))
    op.alter_column('restaurant_settings', 'allow_cancel_preparing',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'allow_cancel_ready',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'allow_modify_preparing',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'order_accept_timeout_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'order_expire_timeout_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_settings', 'order_expire_timeout_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('15'),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'order_accept_timeout_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'allow_modify_preparing',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'allow_cancel_ready',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'allow_cancel_preparing',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_column('restaurant_settings', 'service_fee_type')
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_column('offers', 'usage_limit_per_customer')
    # ### end Alembic commands ###