"""auto update

Revision ID: aeebad7f6456
Revises: 6caad6e08bac
Create Date: 2026-07-19 07:05:33.406297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeebad7f6456'
down_revision: Union[str, Sequence[str], None] = '6caad6e08bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('categories_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.add_column('orders', sa.Column('service_fee', sa.Float(), server_default='0', nullable=True))
    op.add_column('orders', sa.Column('small_order_fee', sa.Float(), server_default='0', nullable=True))
    op.add_column('restaurant_settings', sa.Column('service_fee_enabled', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('restaurant_settings', sa.Column('service_fee_amount', sa.Float(), server_default='0', nullable=True))
    op.add_column('restaurant_settings', sa.Column('small_order_fee_enabled', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('restaurant_settings', sa.Column('small_order_fee_amount', sa.Float(), server_default='0', nullable=True))
    op.add_column('restaurant_settings', sa.Column('small_order_fee_threshold', sa.Float(), server_default='20', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_settings', 'small_order_fee_threshold')
    op.drop_column('restaurant_settings', 'small_order_fee_amount')
    op.drop_column('restaurant_settings', 'small_order_fee_enabled')
    op.drop_column('restaurant_settings', 'service_fee_amount')
    op.drop_column('restaurant_settings', 'service_fee_enabled')
    op.drop_column('orders', 'small_order_fee')
    op.drop_column('orders', 'service_fee')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###