"""auto update

Revision ID: b39b3e9a2496
Revises: aeebad7f6456
Create Date: 2026-07-19 07:29:24.213761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39b3e9a2496'
down_revision: Union[str, Sequence[str], None] = 'aeebad7f6456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_notifications_id'), 'app_notifications', ['id'], unique=False)
    op.add_column('deals', sa.Column('discount_type', sa.String(), server_default='none', nullable=True))
    op.add_column('deals', sa.Column('discount_value', sa.Float(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'discount_value')
    op.drop_column('deals', 'discount_type')
    op.drop_index(op.f('ix_app_notifications_id'), table_name='app_notifications')
    op.drop_table('app_notifications')
    # ### end Alembic commands ###