"""auto update

Revision ID: ec04de65b581
Revises: b39b3e9a2496
Create Date: 2026-07-19 08:32:27.966776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec04de65b581'
down_revision: Union[str, Sequence[str], None] = 'b39b3e9a2496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_settings', sa.Column('service_fee_applies_to', sa.String(), nullable=True))
    op.add_column('restaurant_settings', sa.Column('cash_enabled_pickup', sa.Boolean(), nullable=True))
    op.add_column('restaurant_settings', sa.Column('card_enabled_pickup', sa.Boolean(), nullable=True))
    op.add_column('restaurant_settings', sa.Column('cash_enabled_delivery', sa.Boolean(), nullable=True))
    op.add_column('restaurant_settings', sa.Column('card_enabled_delivery', sa.Boolean(), nullable=True))
    op.alter_column('restaurant_settings', 'restaurant_name',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('restaurant_settings', 'phone',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'address',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'opening_hours',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'logo_url',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'restaurant_status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'busy_message',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'estimated_wait_time',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'delivery_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'delivery_charges',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'estimated_delivery_time',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'restaurant_lat',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'restaurant_lng',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'near_radius',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'far_radius',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'near_charge',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'far_charge',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'auto_schedule_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'auto_open_time',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'auto_close_time',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'service_fee_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'service_fee_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'small_order_fee_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'small_order_fee_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'small_order_fee_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_settings', 'small_order_fee_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'20'::double precision"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'small_order_fee_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'small_order_fee_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'service_fee_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'service_fee_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'auto_close_time',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'02:00'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'auto_open_time',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'15:00'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'auto_schedule_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'far_charge',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'15'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'near_charge',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'5'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'far_radius',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'15'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'near_radius',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'5'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'restaurant_lng',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'56.3264'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'restaurant_lat',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'25.1288'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'estimated_delivery_time',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'30-45 min'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'delivery_charges',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'5'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'delivery_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'estimated_wait_time',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'30-45 min'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'busy_message',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'We are currently very busy. Your order may take longer than usual.'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'restaurant_status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'logo_url',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'opening_hours',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Daily 3:00 PM - 2:00 AM'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'address',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Murbah, Fujairah, UAE'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'phone',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'+971 54 294 0112'::character varying"),
               existing_nullable=True)
    op.alter_column('restaurant_settings', 'restaurant_name',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Vita Napoli'::character varying"),
               existing_nullable=False)
    op.drop_column('restaurant_settings', 'card_enabled_delivery')
    op.drop_column('restaurant_settings', 'cash_enabled_delivery')
    op.drop_column('restaurant_settings', 'card_enabled_pickup')
    op.drop_column('restaurant_settings', 'cash_enabled_pickup')
    op.drop_column('restaurant_settings', 'service_fee_applies_to')
    # ### end Alembic commands ###